### ISSUE TITLE
How to create multiple misssion in GCS? and I want to simply work with more then one node but the problem is hare i am not able to show more than one node . please tell me how can i do it?

### ISSUE THREAD

**Issue by sivdesh** [uavos/apx-gcs#25] opened 2021-09-08 04:35 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by uavinda** [comment] 2021-09-09 19:39
Duplicate of #22

The future APXFW release will fix this issue.

**Closed by uavinda** 2021-09-09 19:39 UTC
