### ISSUE TITLE
How to add multiple virtual uav in GCS or Can explain how to show multiple UAV same time on display?

### ISSUE THREAD

**Issue by sivdesh** [uavos/apx-gcs#24] opened 2021-09-07 05:19 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS]

**Additional context**

**Comment by uavinda** [comment] 2021-09-07 17:58
Duplicate of #22

**Closed by uavinda** 2021-09-07 17:58 UTC
Labels: bug
